apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-owner-sa
  namespace: product-team
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: business-analyst-sa
  namespace: product-team
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer-sa
  namespace: product-team
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operations-engineer-sa
  namespace: product-team
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-engineer-sa
  namespace: product-team